/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/7mnfiKtGH115hHeT/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#fefefe"]} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <group
            name="Flowers"
            position={[95.31, 134.35, 44.45]}
            scale={[0.29, 0.24, 0.26]}
          >
            <group name="Flowers 2">
              <group
                name="Flowers 21"
                position={[-171.62, 0, 246.58]}
                rotation={[-Math.PI, 0.45, -Math.PI]}
                scale={[1.02, 1, 0.99]}
              >
                <group
                  name="Flowers 22"
                  position={[45.16, -0.07, 102.66]}
                  rotation={[0, 0, 0]}
                  scale={[1.02, 0.98, 1]}
                >
                  <group
                    name="flowers"
                    position={[-4.25, 112.27, 24.49]}
                    scale={2.1}
                  >
                    <group
                      name="Group 3"
                      position={[-6.09, 0, -6.77]}
                      rotation={[-3.09, 0.99, 2.85]}
                      scale={0.45}
                    >
                      <mesh
                        name="Sphere 9"
                        geometry={nodes["Sphere 9"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-8.75, 52.5, 11.79]}
                        rotation={[-0.48, -0.77, 0.47]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 8"
                        geometry={nodes["Sphere 8"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-14.09, 60.35, -2.01]}
                        rotation={[-1.6, -0.87, 0.01]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 7"
                        geometry={nodes["Sphere 7"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-5.81, 52.79, -14.94]}
                        rotation={[-2.84, -0.38, -0.8]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 6"
                        geometry={nodes["Sphere 6"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[6.67, 40.84, -17.64]}
                        rotation={[2.8, 0.2, -0.69]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 5"
                        geometry={nodes["Sphere 5"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[14.77, 33.96, -9.85]}
                        rotation={[1.93, 0.66, -0.29]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 4"
                        geometry={nodes["Sphere 4"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[14.65, 32.29, 3.91]}
                        rotation={[1.21, 0.57, 0.36]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 3"
                        geometry={nodes["Sphere 3"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[8.72, 34.59, 16.01]}
                        rotation={[0.7, 0.2, 0.74]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 2"
                        geometry={nodes["Sphere 2"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-2.35, 43, 19.91]}
                        rotation={[0.31, -0.28, 0.86]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere"
                        geometry={nodes.Sphere.geometry}
                        material={materials.green_v2}
                        castShadow
                        receiveShadow
                        position={[3.77, 47.61, 0.13]}
                        rotation={[0, 0, 0.82]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Cube 2"
                        geometry={nodes["Cube 2"].geometry}
                        material={materials.green_v1}
                        castShadow
                        receiveShadow
                        position={[-25.1, 10.36, -3.38]}
                      />
                    </group>
                    <group
                      name="Group 2"
                      position={[-1.35, 1.49, 17.43]}
                      rotation={[0, -1.53, -0.06]}
                      scale={0.45}
                    >
                      <mesh
                        name="Sphere 91"
                        geometry={nodes["Sphere 91"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-8.75, 52.5, 11.79]}
                        rotation={[-0.48, -0.77, 0.47]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 81"
                        geometry={nodes["Sphere 81"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-14.09, 60.35, -2.01]}
                        rotation={[-1.6, -0.87, 0.01]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 71"
                        geometry={nodes["Sphere 71"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-5.81, 52.79, -14.94]}
                        rotation={[-2.84, -0.38, -0.8]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 61"
                        geometry={nodes["Sphere 61"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[6.67, 40.84, -17.64]}
                        rotation={[2.8, 0.2, -0.69]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 51"
                        geometry={nodes["Sphere 51"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[14.77, 33.96, -9.85]}
                        rotation={[1.93, 0.66, -0.29]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 41"
                        geometry={nodes["Sphere 41"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[14.65, 32.29, 3.91]}
                        rotation={[1.21, 0.57, 0.36]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 31"
                        geometry={nodes["Sphere 31"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[8.72, 34.59, 16.01]}
                        rotation={[0.7, 0.2, 0.74]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 21"
                        geometry={nodes["Sphere 21"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-2.35, 43, 19.91]}
                        rotation={[0.31, -0.28, 0.86]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere1"
                        geometry={nodes.Sphere1.geometry}
                        material={materials.green_v2}
                        castShadow
                        receiveShadow
                        position={[3.77, 47.61, 0.13]}
                        rotation={[0, 0, 0.82]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Cube 21"
                        geometry={nodes["Cube 21"].geometry}
                        material={materials.green_v1}
                        castShadow
                        receiveShadow
                        position={[-25.1, 10.36, -3.38]}
                      />
                    </group>
                    <group
                      name="Group"
                      position={[19.32, 1.86, 8.59]}
                      scale={0.45}
                    >
                      <mesh
                        name="Sphere 92"
                        geometry={nodes["Sphere 92"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-8.75, 52.5, 11.79]}
                        rotation={[-0.48, -0.77, 0.47]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 82"
                        geometry={nodes["Sphere 82"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-14.09, 60.35, -2.01]}
                        rotation={[-1.6, -0.87, 0.01]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 72"
                        geometry={nodes["Sphere 72"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-5.81, 52.79, -14.94]}
                        rotation={[-2.84, -0.38, -0.8]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 62"
                        geometry={nodes["Sphere 62"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[6.67, 40.84, -17.64]}
                        rotation={[2.8, 0.2, -0.69]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 52"
                        geometry={nodes["Sphere 52"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[14.77, 33.96, -9.85]}
                        rotation={[1.93, 0.66, -0.29]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 42"
                        geometry={nodes["Sphere 42"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[14.65, 32.29, 3.91]}
                        rotation={[1.21, 0.57, 0.36]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 32"
                        geometry={nodes["Sphere 32"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[8.72, 34.59, 16.01]}
                        rotation={[0.7, 0.2, 0.74]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere 22"
                        geometry={nodes["Sphere 22"].geometry}
                        material={materials.yellow}
                        castShadow
                        receiveShadow
                        position={[-2.35, 43, 19.91]}
                        rotation={[0.31, -0.28, 0.86]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Sphere2"
                        geometry={nodes.Sphere2.geometry}
                        material={materials.green_v2}
                        castShadow
                        receiveShadow
                        position={[3.77, 47.61, 0.13]}
                        rotation={[0, 0, 0.82]}
                        scale={[0.13, 0.36, 0.36]}
                      />
                      <mesh
                        name="Cube 22"
                        geometry={nodes["Cube 22"].geometry}
                        material={materials.green_v1}
                        castShadow
                        receiveShadow
                        position={[-25.1, 10.36, -3.38]}
                      />
                    </group>
                  </group>
                  <mesh
                    name="jar"
                    geometry={nodes.jar.geometry}
                    material={materials.blue}
                    castShadow
                    receiveShadow
                    position={[2.28, 54.86, 33.67]}
                    scale={0.51}
                  />
                </group>
                <group
                  name="Canna indica_01 2"
                  position={[39.1, 119.46, 178.92]}
                  rotation={[0, 0, 0]}
                  scale={[1.79, 1.02, 1.91]}
                >
                  <group
                    name="flower"
                    position={[-7.02, 223.12, 1.09]}
                    scale={0.52}
                  >
                    <mesh
                      name="Cylinder 11"
                      geometry={nodes["Cylinder 11"].geometry}
                      material={materials.flower}
                      castShadow
                      receiveShadow
                      position={[-1.88, -34.29, 1.78]}
                      rotation={[-2.84, 0.49, 2.56]}
                      scale={1}
                    />
                    <mesh
                      name="Cylinder 10"
                      geometry={nodes["Cylinder 10"].geometry}
                      material={materials.flower}
                      castShadow
                      receiveShadow
                      position={[17.95, -31.09, 2.81]}
                      rotation={[3.09, -0.01, -2.97]}
                      scale={1}
                    />
                  </group>
                  <mesh
                    name="plant"
                    geometry={nodes.plant.geometry}
                    material={materials.grass}
                    castShadow
                    receiveShadow
                    position={[1, 116.82, 3.28]}
                    rotation={[-Math.PI, 0, -Math.PI]}
                    scale={0.52}
                  />
                </group>
                <group
                  name="Canna indica_02 2"
                  position={[-8.4, 112.8, 186.55]}
                  rotation={[0, 0, 0]}
                  scale={[0.59, 0.68, 0.63]}
                >
                  <mesh
                    name="flower1"
                    geometry={nodes.flower1.geometry}
                    material={materials.flower}
                    castShadow
                    receiveShadow
                    position={[1.91, 172.94, 2.19]}
                    scale={0.54}
                  />
                  <mesh
                    name="plant1"
                    geometry={nodes.plant1.geometry}
                    material={materials.grass}
                    castShadow
                    receiveShadow
                    position={[2.23, 79.51, 2.69]}
                    scale={0.54}
                  />
                </group>
                <group
                  name="Canna indica_03 2"
                  position={[17.97, 85.7, 142.64]}
                  rotation={[0, 0, 0]}
                  scale={[1.09, 1.25, 1.16]}
                >
                  <group
                    name="flower2"
                    position={[8.69, 191.6, 0.19]}
                    scale={0.46}
                  >
                    <mesh
                      name="Cylinder 111"
                      geometry={nodes["Cylinder 111"].geometry}
                      material={materials.flower}
                      castShadow
                      receiveShadow
                      position={[-2.66, -26.36, -0.43]}
                      rotation={[-0.3, -0.49, -0.58]}
                      scale={1}
                    />
                    <mesh
                      name="Cylinder 101"
                      geometry={nodes["Cylinder 101"].geometry}
                      material={materials.flower}
                      castShadow
                      receiveShadow
                      position={[-23.41, -21.66, -3.74]}
                      rotation={[0.18, 0.03, 0.16]}
                      scale={1}
                    />
                  </group>
                  <mesh
                    name="plant2"
                    geometry={nodes.plant2.geometry}
                    material={materials.grass}
                    castShadow
                    receiveShadow
                    position={[-0.37, 102.54, -1.09]}
                    scale={0.46}
                  />
                </group>
                <group
                  name="flowers1"
                  position={[-4.25, 112.27, 24.49]}
                  scale={2.1}
                >
                  <group
                    name="Group 31"
                    position={[-6.09, 0, -6.77]}
                    rotation={[-3.09, 0.99, 2.85]}
                    scale={0.45}
                  >
                    <mesh
                      name="Sphere 93"
                      geometry={nodes["Sphere 93"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-8.75, 52.5, 11.79]}
                      rotation={[-0.48, -0.77, 0.47]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 83"
                      geometry={nodes["Sphere 83"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-14.09, 60.35, -2.01]}
                      rotation={[-1.6, -0.87, 0.01]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 73"
                      geometry={nodes["Sphere 73"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-5.81, 52.79, -14.94]}
                      rotation={[-2.84, -0.38, -0.8]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 63"
                      geometry={nodes["Sphere 63"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[6.67, 40.84, -17.64]}
                      rotation={[2.8, 0.2, -0.69]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 53"
                      geometry={nodes["Sphere 53"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[14.77, 33.96, -9.85]}
                      rotation={[1.93, 0.66, -0.29]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 43"
                      geometry={nodes["Sphere 43"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[14.65, 32.29, 3.91]}
                      rotation={[1.21, 0.57, 0.36]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 33"
                      geometry={nodes["Sphere 33"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[8.72, 34.59, 16.01]}
                      rotation={[0.7, 0.2, 0.74]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 23"
                      geometry={nodes["Sphere 23"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-2.35, 43, 19.91]}
                      rotation={[0.31, -0.28, 0.86]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere3"
                      geometry={nodes.Sphere3.geometry}
                      material={materials.green_v2}
                      castShadow
                      receiveShadow
                      position={[3.77, 47.61, 0.13]}
                      rotation={[0, 0, 0.82]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Cube 23"
                      geometry={nodes["Cube 23"].geometry}
                      material={materials.green_v1}
                      castShadow
                      receiveShadow
                      position={[-25.1, 10.36, -3.38]}
                    />
                  </group>
                  <group
                    name="Group 21"
                    position={[-1.35, 1.49, 17.43]}
                    rotation={[0, -1.53, -0.06]}
                    scale={0.45}
                  >
                    <mesh
                      name="Sphere 94"
                      geometry={nodes["Sphere 94"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-8.75, 52.5, 11.79]}
                      rotation={[-0.48, -0.77, 0.47]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 84"
                      geometry={nodes["Sphere 84"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-14.09, 60.35, -2.01]}
                      rotation={[-1.6, -0.87, 0.01]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 74"
                      geometry={nodes["Sphere 74"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-5.81, 52.79, -14.94]}
                      rotation={[-2.84, -0.38, -0.8]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 64"
                      geometry={nodes["Sphere 64"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[6.67, 40.84, -17.64]}
                      rotation={[2.8, 0.2, -0.69]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 54"
                      geometry={nodes["Sphere 54"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[14.77, 33.96, -9.85]}
                      rotation={[1.93, 0.66, -0.29]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 44"
                      geometry={nodes["Sphere 44"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[14.65, 32.29, 3.91]}
                      rotation={[1.21, 0.57, 0.36]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 34"
                      geometry={nodes["Sphere 34"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[8.72, 34.59, 16.01]}
                      rotation={[0.7, 0.2, 0.74]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 24"
                      geometry={nodes["Sphere 24"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-2.35, 43, 19.91]}
                      rotation={[0.31, -0.28, 0.86]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere4"
                      geometry={nodes.Sphere4.geometry}
                      material={materials.green_v2}
                      castShadow
                      receiveShadow
                      position={[3.77, 47.61, 0.13]}
                      rotation={[0, 0, 0.82]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Cube 24"
                      geometry={nodes["Cube 24"].geometry}
                      material={materials.green_v1}
                      castShadow
                      receiveShadow
                      position={[-25.1, 10.36, -3.38]}
                    />
                  </group>
                  <group
                    name="Group1"
                    position={[19.32, 1.86, 8.59]}
                    scale={0.45}
                  >
                    <mesh
                      name="Sphere 95"
                      geometry={nodes["Sphere 95"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-8.75, 52.5, 11.79]}
                      rotation={[-0.48, -0.77, 0.47]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 85"
                      geometry={nodes["Sphere 85"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-14.09, 60.35, -2.01]}
                      rotation={[-1.6, -0.87, 0.01]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 75"
                      geometry={nodes["Sphere 75"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-5.81, 52.79, -14.94]}
                      rotation={[-2.84, -0.38, -0.8]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 65"
                      geometry={nodes["Sphere 65"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[6.67, 40.84, -17.64]}
                      rotation={[2.8, 0.2, -0.69]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 55"
                      geometry={nodes["Sphere 55"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[14.77, 33.96, -9.85]}
                      rotation={[1.93, 0.66, -0.29]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 45"
                      geometry={nodes["Sphere 45"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[14.65, 32.29, 3.91]}
                      rotation={[1.21, 0.57, 0.36]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 35"
                      geometry={nodes["Sphere 35"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[8.72, 34.59, 16.01]}
                      rotation={[0.7, 0.2, 0.74]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere 25"
                      geometry={nodes["Sphere 25"].geometry}
                      material={materials.yellow}
                      castShadow
                      receiveShadow
                      position={[-2.35, 43, 19.91]}
                      rotation={[0.31, -0.28, 0.86]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Sphere5"
                      geometry={nodes.Sphere5.geometry}
                      material={materials.green_v2}
                      castShadow
                      receiveShadow
                      position={[3.77, 47.61, 0.13]}
                      rotation={[0, 0, 0.82]}
                      scale={[0.13, 0.36, 0.36]}
                    />
                    <mesh
                      name="Cube 25"
                      geometry={nodes["Cube 25"].geometry}
                      material={materials.green_v1}
                      castShadow
                      receiveShadow
                      position={[-25.1, 10.36, -3.38]}
                    />
                  </group>
                </group>
                <mesh
                  name="jar1"
                  geometry={nodes.jar1.geometry}
                  material={materials.blue}
                  castShadow
                  receiveShadow
                  position={[2.28, 54.86, 33.67]}
                  scale={0.51}
                />
              </group>
              <group
                name="Canna indica_01 21"
                position={[-133.61, 119.53, 181.37]}
                rotation={[-Math.PI, 0.45, -Math.PI]}
                scale={[1.79, 1.04, 1.88]}
              >
                <group
                  name="flower3"
                  position={[-7.02, 223.12, 1.09]}
                  scale={0.52}
                >
                  <mesh
                    name="Cylinder 112"
                    geometry={nodes["Cylinder 112"].geometry}
                    material={materials.flower}
                    castShadow
                    receiveShadow
                    position={[-1.88, -34.29, 1.78]}
                    rotation={[-2.84, 0.49, 2.56]}
                    scale={1}
                  />
                  <mesh
                    name="Cylinder 102"
                    geometry={nodes["Cylinder 102"].geometry}
                    material={materials.flower}
                    castShadow
                    receiveShadow
                    position={[17.95, -31.09, 2.81]}
                    rotation={[3.09, -0.01, -2.97]}
                    scale={1}
                  />
                </group>
                <mesh
                  name="plant3"
                  geometry={nodes.plant3.geometry}
                  material={materials.grass}
                  castShadow
                  receiveShadow
                  position={[1, 116.82, 3.28]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={0.52}
                />
              </group>
              <group
                name="Canna indica_02 21"
                position={[-86.76, 112.87, 195.43]}
                rotation={[-Math.PI, 0.45, -Math.PI]}
                scale={[0.59, 0.69, 0.62]}
              >
                <mesh
                  name="flower4"
                  geometry={nodes.flower4.geometry}
                  material={materials.flower}
                  castShadow
                  receiveShadow
                  position={[1.91, 172.94, 2.19]}
                  scale={0.54}
                />
                <mesh
                  name="plant4"
                  geometry={nodes.plant4.geometry}
                  material={materials.grass}
                  castShadow
                  receiveShadow
                  position={[2.23, 79.51, 2.69]}
                  scale={0.54}
                />
              </group>
              <group
                name="Canna indica_03 21"
                position={[-129.65, 85.77, 222.94]}
                rotation={[-Math.PI, 0.45, -Math.PI]}
                scale={[1.09, 1.27, 1.14]}
              >
                <group
                  name="flower5"
                  position={[8.69, 191.6, 0.19]}
                  scale={0.46}
                >
                  <mesh
                    name="Cylinder 113"
                    geometry={nodes["Cylinder 113"].geometry}
                    material={materials.flower}
                    castShadow
                    receiveShadow
                    position={[-2.66, -26.36, -0.43]}
                    rotation={[-0.3, -0.49, -0.58]}
                    scale={1}
                  />
                  <mesh
                    name="Cylinder 103"
                    geometry={nodes["Cylinder 103"].geometry}
                    material={materials.flower}
                    castShadow
                    receiveShadow
                    position={[-23.41, -21.66, -3.74]}
                    rotation={[0.18, 0.03, 0.16]}
                    scale={1}
                  />
                </group>
                <mesh
                  name="plant5"
                  geometry={nodes.plant5.geometry}
                  material={materials.grass}
                  castShadow
                  receiveShadow
                  position={[-0.37, 102.54, -1.09]}
                  scale={0.46}
                />
              </group>
              <group
                name="flowers2"
                position={[-4.25, 112.27, 24.49]}
                scale={2.1}
              >
                <group
                  name="Group 32"
                  position={[-6.09, 0, -6.77]}
                  rotation={[-3.09, 0.99, 2.85]}
                  scale={0.45}
                >
                  <mesh
                    name="Sphere 96"
                    geometry={nodes["Sphere 96"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-8.75, 52.5, 11.79]}
                    rotation={[-0.48, -0.77, 0.47]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 86"
                    geometry={nodes["Sphere 86"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-14.09, 60.35, -2.01]}
                    rotation={[-1.6, -0.87, 0.01]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 76"
                    geometry={nodes["Sphere 76"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-5.81, 52.79, -14.94]}
                    rotation={[-2.84, -0.38, -0.8]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 66"
                    geometry={nodes["Sphere 66"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[6.67, 40.84, -17.64]}
                    rotation={[2.8, 0.2, -0.69]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 56"
                    geometry={nodes["Sphere 56"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[14.77, 33.96, -9.85]}
                    rotation={[1.93, 0.66, -0.29]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 46"
                    geometry={nodes["Sphere 46"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[14.65, 32.29, 3.91]}
                    rotation={[1.21, 0.57, 0.36]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 36"
                    geometry={nodes["Sphere 36"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[8.72, 34.59, 16.01]}
                    rotation={[0.7, 0.2, 0.74]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 26"
                    geometry={nodes["Sphere 26"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-2.35, 43, 19.91]}
                    rotation={[0.31, -0.28, 0.86]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere6"
                    geometry={nodes.Sphere6.geometry}
                    material={materials.green_v2}
                    castShadow
                    receiveShadow
                    position={[3.77, 47.61, 0.13]}
                    rotation={[0, 0, 0.82]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Cube 26"
                    geometry={nodes["Cube 26"].geometry}
                    material={materials.green_v1}
                    castShadow
                    receiveShadow
                    position={[-25.1, 10.36, -3.38]}
                  />
                </group>
                <group
                  name="Group 22"
                  position={[-1.35, 1.49, 17.43]}
                  rotation={[0, -1.53, -0.06]}
                  scale={0.45}
                >
                  <mesh
                    name="Sphere 97"
                    geometry={nodes["Sphere 97"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-8.75, 52.5, 11.79]}
                    rotation={[-0.48, -0.77, 0.47]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 87"
                    geometry={nodes["Sphere 87"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-14.09, 60.35, -2.01]}
                    rotation={[-1.6, -0.87, 0.01]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 77"
                    geometry={nodes["Sphere 77"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-5.81, 52.79, -14.94]}
                    rotation={[-2.84, -0.38, -0.8]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 67"
                    geometry={nodes["Sphere 67"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[6.67, 40.84, -17.64]}
                    rotation={[2.8, 0.2, -0.69]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 57"
                    geometry={nodes["Sphere 57"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[14.77, 33.96, -9.85]}
                    rotation={[1.93, 0.66, -0.29]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 47"
                    geometry={nodes["Sphere 47"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[14.65, 32.29, 3.91]}
                    rotation={[1.21, 0.57, 0.36]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 37"
                    geometry={nodes["Sphere 37"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[8.72, 34.59, 16.01]}
                    rotation={[0.7, 0.2, 0.74]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 27"
                    geometry={nodes["Sphere 27"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-2.35, 43, 19.91]}
                    rotation={[0.31, -0.28, 0.86]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere7"
                    geometry={nodes.Sphere7.geometry}
                    material={materials.green_v2}
                    castShadow
                    receiveShadow
                    position={[3.77, 47.61, 0.13]}
                    rotation={[0, 0, 0.82]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Cube 27"
                    geometry={nodes["Cube 27"].geometry}
                    material={materials.green_v1}
                    castShadow
                    receiveShadow
                    position={[-25.1, 10.36, -3.38]}
                  />
                </group>
                <group
                  name="Group2"
                  position={[19.32, 1.86, 8.59]}
                  scale={0.45}
                >
                  <mesh
                    name="Sphere 98"
                    geometry={nodes["Sphere 98"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-8.75, 52.5, 11.79]}
                    rotation={[-0.48, -0.77, 0.47]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 88"
                    geometry={nodes["Sphere 88"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-14.09, 60.35, -2.01]}
                    rotation={[-1.6, -0.87, 0.01]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 78"
                    geometry={nodes["Sphere 78"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-5.81, 52.79, -14.94]}
                    rotation={[-2.84, -0.38, -0.8]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 68"
                    geometry={nodes["Sphere 68"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[6.67, 40.84, -17.64]}
                    rotation={[2.8, 0.2, -0.69]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 58"
                    geometry={nodes["Sphere 58"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[14.77, 33.96, -9.85]}
                    rotation={[1.93, 0.66, -0.29]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 48"
                    geometry={nodes["Sphere 48"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[14.65, 32.29, 3.91]}
                    rotation={[1.21, 0.57, 0.36]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 38"
                    geometry={nodes["Sphere 38"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[8.72, 34.59, 16.01]}
                    rotation={[0.7, 0.2, 0.74]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere 28"
                    geometry={nodes["Sphere 28"].geometry}
                    material={materials.yellow}
                    castShadow
                    receiveShadow
                    position={[-2.35, 43, 19.91]}
                    rotation={[0.31, -0.28, 0.86]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Sphere8"
                    geometry={nodes.Sphere8.geometry}
                    material={materials.green_v2}
                    castShadow
                    receiveShadow
                    position={[3.77, 47.61, 0.13]}
                    rotation={[0, 0, 0.82]}
                    scale={[0.13, 0.36, 0.36]}
                  />
                  <mesh
                    name="Cube 28"
                    geometry={nodes["Cube 28"].geometry}
                    material={materials.green_v1}
                    castShadow
                    receiveShadow
                    position={[-25.1, 10.36, -3.38]}
                  />
                </group>
              </group>
              <mesh
                name="jar2"
                geometry={nodes.jar2.geometry}
                material={materials.blue}
                castShadow
                receiveShadow
                position={[2.28, 54.86, 33.67]}
                scale={0.51}
              />
            </group>
            <group
              name="Canna indica_01 22"
              position={[-8.29, 119.53, 76.56]}
              scale={[1.76, 1.04, 1.9]}
            >
              <group
                name="flower6"
                position={[-7.02, 223.12, 1.09]}
                scale={0.52}
              >
                <mesh
                  name="Cylinder 114"
                  geometry={nodes["Cylinder 114"].geometry}
                  material={materials.flower}
                  castShadow
                  receiveShadow
                  position={[-1.88, -34.29, 1.78]}
                  rotation={[-2.84, 0.49, 2.56]}
                  scale={1}
                />
                <mesh
                  name="Cylinder 104"
                  geometry={nodes["Cylinder 104"].geometry}
                  material={materials.flower}
                  castShadow
                  receiveShadow
                  position={[17.95, -31.09, 2.81]}
                  rotation={[3.09, -0.01, -2.97]}
                  scale={1}
                />
              </group>
              <mesh
                name="plant6"
                geometry={nodes.plant6.geometry}
                material={materials.grass}
                castShadow
                receiveShadow
                position={[1, 116.82, 3.28]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={0.52}
              />
            </group>
            <group
              name="Canna indica_02 22"
              position={[-56.08, 112.87, 85.69]}
              scale={[0.58, 0.69, 0.63]}
            >
              <mesh
                name="flower7"
                geometry={nodes.flower7.geometry}
                material={materials.flower}
                castShadow
                receiveShadow
                position={[1.91, 172.94, 2.19]}
                scale={0.54}
              />
              <mesh
                name="plant7"
                geometry={nodes.plant7.geometry}
                material={materials.grass}
                castShadow
                receiveShadow
                position={[2.23, 79.51, 2.69]}
                scale={0.54}
              />
            </group>
            <group
              name="Canna indica_03 22"
              position={[-28.4, 85.77, 40.89]}
              rotation={[0, 0, 0]}
              scale={[1.07, 1.27, 1.16]}
            >
              <group name="flower8" position={[8.69, 191.6, 0.19]} scale={0.46}>
                <mesh
                  name="Cylinder 115"
                  geometry={nodes["Cylinder 115"].geometry}
                  material={materials.flower}
                  castShadow
                  receiveShadow
                  position={[-2.66, -26.36, -0.43]}
                  rotation={[-0.3, -0.49, -0.58]}
                  scale={1}
                />
                <mesh
                  name="Cylinder 105"
                  geometry={nodes["Cylinder 105"].geometry}
                  material={materials.flower}
                  castShadow
                  receiveShadow
                  position={[-23.41, -21.66, -3.74]}
                  rotation={[0.18, 0.03, 0.16]}
                  scale={1}
                />
              </group>
              <mesh
                name="plant8"
                geometry={nodes.plant8.geometry}
                material={materials.grass}
                castShadow
                receiveShadow
                position={[-0.37, 102.54, -1.09]}
                scale={0.46}
              />
            </group>
            <mesh
              name="Rectangle 2"
              geometry={nodes["Rectangle 2"].geometry}
              material={materials["Rectangle 2 Material"]}
              castShadow
              receiveShadow
              position={[50.01, -12.88, 101.81]}
              rotation={[-1.57, 0, 0]}
              scale={[3.5, 3.76, 4.21]}
            />
            <group
              name="flowers3"
              position={[-4.25, 112.27, 24.49]}
              scale={2.1}
            >
              <group
                name="Group 33"
                position={[-6.09, 0, -6.77]}
                rotation={[-3.09, 0.99, 2.85]}
                scale={0.45}
              >
                <mesh
                  name="Sphere 99"
                  geometry={nodes["Sphere 99"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-8.75, 52.5, 11.79]}
                  rotation={[-0.48, -0.77, 0.47]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 89"
                  geometry={nodes["Sphere 89"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-14.09, 60.35, -2.01]}
                  rotation={[-1.6, -0.87, 0.01]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 79"
                  geometry={nodes["Sphere 79"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-5.81, 52.79, -14.94]}
                  rotation={[-2.84, -0.38, -0.8]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 69"
                  geometry={nodes["Sphere 69"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[6.67, 40.84, -17.64]}
                  rotation={[2.8, 0.2, -0.69]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 59"
                  geometry={nodes["Sphere 59"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[14.77, 33.96, -9.85]}
                  rotation={[1.93, 0.66, -0.29]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 49"
                  geometry={nodes["Sphere 49"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[14.65, 32.29, 3.91]}
                  rotation={[1.21, 0.57, 0.36]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 39"
                  geometry={nodes["Sphere 39"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[8.72, 34.59, 16.01]}
                  rotation={[0.7, 0.2, 0.74]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 29"
                  geometry={nodes["Sphere 29"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-2.35, 43, 19.91]}
                  rotation={[0.31, -0.28, 0.86]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere9"
                  geometry={nodes.Sphere9.geometry}
                  material={materials.green_v2}
                  castShadow
                  receiveShadow
                  position={[3.77, 47.61, 0.13]}
                  rotation={[0, 0, 0.82]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Cube 29"
                  geometry={nodes["Cube 29"].geometry}
                  material={materials.green_v1}
                  castShadow
                  receiveShadow
                  position={[-25.1, 10.36, -3.38]}
                />
              </group>
              <group
                name="Group 23"
                position={[-1.35, 1.49, 17.43]}
                rotation={[0, -1.53, -0.06]}
                scale={0.45}
              >
                <mesh
                  name="Sphere 910"
                  geometry={nodes["Sphere 910"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-8.75, 52.5, 11.79]}
                  rotation={[-0.48, -0.77, 0.47]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 810"
                  geometry={nodes["Sphere 810"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-14.09, 60.35, -2.01]}
                  rotation={[-1.6, -0.87, 0.01]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 710"
                  geometry={nodes["Sphere 710"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-5.81, 52.79, -14.94]}
                  rotation={[-2.84, -0.38, -0.8]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 610"
                  geometry={nodes["Sphere 610"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[6.67, 40.84, -17.64]}
                  rotation={[2.8, 0.2, -0.69]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 510"
                  geometry={nodes["Sphere 510"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[14.77, 33.96, -9.85]}
                  rotation={[1.93, 0.66, -0.29]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 410"
                  geometry={nodes["Sphere 410"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[14.65, 32.29, 3.91]}
                  rotation={[1.21, 0.57, 0.36]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 310"
                  geometry={nodes["Sphere 310"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[8.72, 34.59, 16.01]}
                  rotation={[0.7, 0.2, 0.74]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 210"
                  geometry={nodes["Sphere 210"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-2.35, 43, 19.91]}
                  rotation={[0.31, -0.28, 0.86]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere10"
                  geometry={nodes.Sphere10.geometry}
                  material={materials.green_v2}
                  castShadow
                  receiveShadow
                  position={[3.77, 47.61, 0.13]}
                  rotation={[0, 0, 0.82]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Cube 210"
                  geometry={nodes["Cube 210"].geometry}
                  material={materials.green_v1}
                  castShadow
                  receiveShadow
                  position={[-25.1, 10.36, -3.38]}
                />
              </group>
              <group name="Group3" position={[19.32, 1.86, 8.59]} scale={0.45}>
                <mesh
                  name="Sphere 911"
                  geometry={nodes["Sphere 911"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-8.75, 52.5, 11.79]}
                  rotation={[-0.48, -0.77, 0.47]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 811"
                  geometry={nodes["Sphere 811"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-14.09, 60.35, -2.01]}
                  rotation={[-1.6, -0.87, 0.01]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 711"
                  geometry={nodes["Sphere 711"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-5.81, 52.79, -14.94]}
                  rotation={[-2.84, -0.38, -0.8]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 611"
                  geometry={nodes["Sphere 611"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[6.67, 40.84, -17.64]}
                  rotation={[2.8, 0.2, -0.69]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 511"
                  geometry={nodes["Sphere 511"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[14.77, 33.96, -9.85]}
                  rotation={[1.93, 0.66, -0.29]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 411"
                  geometry={nodes["Sphere 411"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[14.65, 32.29, 3.91]}
                  rotation={[1.21, 0.57, 0.36]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 311"
                  geometry={nodes["Sphere 311"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[8.72, 34.59, 16.01]}
                  rotation={[0.7, 0.2, 0.74]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere 211"
                  geometry={nodes["Sphere 211"].geometry}
                  material={materials.yellow}
                  castShadow
                  receiveShadow
                  position={[-2.35, 43, 19.91]}
                  rotation={[0.31, -0.28, 0.86]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Sphere11"
                  geometry={nodes.Sphere11.geometry}
                  material={materials.green_v2}
                  castShadow
                  receiveShadow
                  position={[3.77, 47.61, 0.13]}
                  rotation={[0, 0, 0.82]}
                  scale={[0.13, 0.36, 0.36]}
                />
                <mesh
                  name="Cube 211"
                  geometry={nodes["Cube 211"].geometry}
                  material={materials.green_v1}
                  castShadow
                  receiveShadow
                  position={[-25.1, 10.36, -3.38]}
                />
              </group>
            </group>
            <mesh
              name="jar3"
              geometry={nodes.jar3.geometry}
              material={materials.blue}
              castShadow
              receiveShadow
              position={[2.28, 54.86, 33.67]}
              scale={0.51}
            />
          </group>
          <group
            name="Canna indica_01"
            position={[92.94, 163.05, 64.62]}
            scale={[0.5, 0.25, 0.5]}
          >
            <group name="flower9" position={[-7.02, 223.12, 1.09]} scale={0.52}>
              <mesh
                name="Cylinder 116"
                geometry={nodes["Cylinder 116"].geometry}
                material={materials.flower}
                castShadow
                receiveShadow
                position={[-1.88, -34.29, 1.78]}
                rotation={[-2.84, 0.49, 2.56]}
                scale={1}
              />
              <mesh
                name="Cylinder 106"
                geometry={nodes["Cylinder 106"].geometry}
                material={materials.flower}
                castShadow
                receiveShadow
                position={[17.95, -31.09, 2.81]}
                rotation={[3.09, -0.01, -2.97]}
                scale={1}
              />
            </group>
            <mesh
              name="plant9"
              geometry={nodes.plant9.geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[1, 116.82, 3.28]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={0.52}
            />
          </group>
          <group
            name="Canna indica_02"
            position={[79.3, 161.45, 67.02]}
            scale={0.17}
          >
            <mesh
              name="flower10"
              geometry={nodes.flower10.geometry}
              material={materials.flower}
              castShadow
              receiveShadow
              position={[1.91, 172.94, 2.19]}
              scale={0.54}
            />
            <mesh
              name="plant10"
              geometry={nodes.plant10.geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[2.23, 79.51, 2.69]}
              scale={0.54}
            />
          </group>
          <group
            name="Canna indica_03"
            position={[87.21, 154.95, 55.22]}
            rotation={[0, 0, 0]}
            scale={0.31}
          >
            <group name="flower11" position={[8.69, 191.6, 0.19]} scale={0.46}>
              <mesh
                name="Cylinder 117"
                geometry={nodes["Cylinder 117"].geometry}
                material={materials.flower}
                castShadow
                receiveShadow
                position={[-2.66, -26.36, -0.43]}
                rotation={[-0.3, -0.49, -0.58]}
                scale={1}
              />
              <mesh
                name="Cylinder 107"
                geometry={nodes["Cylinder 107"].geometry}
                material={materials.flower}
                castShadow
                receiveShadow
                position={[-23.41, -21.66, -3.74]}
                rotation={[0.18, 0.03, 0.16]}
                scale={1}
              />
            </group>
            <mesh
              name="plant11"
              geometry={nodes.plant11.geometry}
              material={materials.grass}
              castShadow
              receiveShadow
              position={[-0.37, 102.54, -1.09]}
              scale={0.46}
            />
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[353.27, 431.26, 454.17]}
          />
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials["Rectangle Material"]}
            castShadow
            receiveShadow
            position={[109.58, 131.26, 71.27]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <OrthographicCamera
            name="1"
            makeDefault={true}
            far={10000}
            near={-50000}
          />
          <hemisphereLight
            name="Default Ambient Light"
            intensity={0.75}
            color="#82c441"
          />
        </scene>
      </group>
    </>
  );
}
